/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen2p2_juanflores;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author JD
 */
public class Principal extends javax.swing.JFrame {

   
    Usuario user;
    Cliente client;
    Artistas artist;
    Lanzamiento lanza;
    Cancion cancion;
    Album alb;
    ArrayList<Usuario>usuarios = new ArrayList();
    ArrayList<Cancion>cancioness = new ArrayList();
    ArrayList<Single>singles = new ArrayList();
    ArrayList<Lanzamiento>lanzas = new ArrayList();
    
    public Principal() {
        initComponents();
       fillCB();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tp_artista = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_tit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_fechaCrear = new javax.swing.JTextField();
        btn_lanzamiento = new javax.swing.JButton();
        cb_elegir = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cb_lanza = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbol = new javax.swing.JTree();
        btn_arbol = new javax.swing.JButton();
        tp_cliente = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        canciones = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_titulo = new javax.swing.JTextField();
        txt_tiempo = new javax.swing.JTextField();
        btn_cancion = new javax.swing.JButton();
        btn_finalizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_contraseña = new javax.swing.JTextField();
        txt_edad = new javax.swing.JSpinner();
        artistaCheck = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        cb_users = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btn_iniciar = new javax.swing.JButton();
        txt_nombreArtistico = new javax.swing.JTextField();
        btn_crearUsuario = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_contra = new javax.swing.JTextField();

        jLabel8.setText("titulo");

        txt_tit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_titActionPerformed(evt);
            }
        });

        jLabel9.setText("fecha de creacion");

        btn_lanzamiento.setText("crear lanzamiento");
        btn_lanzamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lanzamientoMouseClicked(evt);
            }
        });

        cb_elegir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Album", "single" }));
        cb_elegir.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_elegirItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel9)
                .addGap(39, 39, 39)
                .addComponent(txt_fechaCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel8)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_tit, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(cb_elegir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_lanzamiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(396, 487, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(cb_elegir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_fechaCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(btn_lanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );

        jTabbedPane1.addTab("crear lanzamiento", jPanel1);

        jLabel15.setText("tiempo");

        jLabel16.setText("Canciones");

        jLabel17.setText("nombre");

        jButton1.setText("Agregar");

        cb_lanza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_lanzaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(cb_lanza, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(431, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel16)
                .addGap(35, 35, 35)
                .addComponent(cb_lanza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Canciones", jPanel2);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Padre");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Albumes");
        treeNode1.add(treeNode2);
        arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(arbol);

        btn_arbol.setText("Actualizar ARBOL");
        btn_arbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_arbolMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(btn_arbol, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(385, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_arbol, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Arbol Lanzamientos", jPanel3);

        javax.swing.GroupLayout tp_artistaLayout = new javax.swing.GroupLayout(tp_artista.getContentPane());
        tp_artista.getContentPane().setLayout(tp_artistaLayout);
        tp_artistaLayout.setHorizontalGroup(
            tp_artistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        tp_artistaLayout.setVerticalGroup(
            tp_artistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 869, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Crear lista de Reproduccion", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 869, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Listas de reproduccion", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 869, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("listas", jPanel6);

        javax.swing.GroupLayout tp_clienteLayout = new javax.swing.GroupLayout(tp_cliente.getContentPane());
        tp_cliente.getContentPane().setLayout(tp_clienteLayout);
        tp_clienteLayout.setHorizontalGroup(
            tp_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        tp_clienteLayout.setVerticalGroup(
            tp_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jLabel10.setText("titulo");

        jLabel11.setText("tiempo");

        btn_cancion.setText("agregar cancion");
        btn_cancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancionMouseClicked(evt);
            }
        });

        btn_finalizar.setText("Finalizar");

        javax.swing.GroupLayout cancionesLayout = new javax.swing.GroupLayout(canciones.getContentPane());
        canciones.getContentPane().setLayout(cancionesLayout);
        cancionesLayout.setHorizontalGroup(
            cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancionesLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cancionesLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(27, 27, 27)
                        .addComponent(txt_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cancionesLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(cancionesLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btn_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addComponent(btn_finalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        cancionesLayout.setVerticalGroup(
            cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancionesLayout.createSequentialGroup()
                .addGroup(cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cancionesLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancionesLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txt_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_finalizar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btn_cancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(88, 88, 88))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INICIO DE SESION");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("USERNAME");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("CONTRASEÑA");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("EDAD");

        artistaCheck.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        artistaCheck.setText("artista");
        artistaCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                artistaCheckMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("NOMBRE ARTISTICO");
        jLabel5.setEnabled(false);

        cb_users.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_usersMouseClicked(evt);
            }
        });

        jLabel6.setText("USER");

        btn_iniciar.setText("Iniciar Sesion");
        btn_iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_iniciarMouseClicked(evt);
            }
        });

        txt_nombreArtistico.setEnabled(false);

        btn_crearUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_crearUsuario.setText("CREAR USUARIO");
        btn_crearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crearUsuarioMouseClicked(evt);
            }
        });

        jLabel7.setText("CONTRA");

        txt_contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(32, 32, 32)
                                .addComponent(txt_nombreArtistico, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(artistaCheck)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(47, 47, 47)
                                        .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(35, 35, 35)
                                        .addComponent(txt_contraseña))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(50, 50, 50)
                                        .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                .addComponent(btn_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_users, 0, 163, Short.MAX_VALUE)
                            .addComponent(txt_contra))))
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(btn_crearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_users, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(btn_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(artistaCheck)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_nombreArtistico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btn_crearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void artistaCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_artistaCheckMouseClicked
        
        if(artistaCheck.isSelected()==true){
            jLabel5.setEnabled(true);
            txt_nombreArtistico.setEnabled(true);
        }else{
            jLabel5.setEnabled(false);
            txt_nombreArtistico.setEnabled(false);
        }
    }//GEN-LAST:event_artistaCheckMouseClicked

    private void btn_crearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearUsuarioMouseClicked
       
        String username = "";
        String contraseña = "";
        int edad;
        String nombreArtistico = "";
        
        
        
        if(artistaCheck.isSelected()==false){
            
            if((int)txt_edad.getValue()<12){
                JOptionPane.showMessageDialog(this, "edad erronea para ser cliente");
            }
            username = txt_username.getText();
            contraseña = txt_contraseña.getText();
            edad = (int) txt_edad.getValue();
            
            client = new Cliente(username, contraseña, edad);
            
            usuarios.add(client);
            
            
        }else{
            if((int)txt_edad.getValue()<18){
                JOptionPane.showMessageDialog(this, "edad erronea para ser artista");
            }
            
            username = txt_username.getText();
            contraseña = txt_contraseña.getText();
            edad = (int) txt_edad.getValue();
            nombreArtistico = txt_nombreArtistico.getText();
            
            artist = new Artistas(nombreArtistico, username, contraseña, edad);  
            
            usuarios.add(artist);
            
        }
        
        FileOutputStream fr = null;
        ObjectOutputStream bw= null;
        
        try {
             File Archivo  = new File ("./Usuarios.JD");
             fr = new FileOutputStream(Archivo);
              bw = new ObjectOutputStream(fr);
             
             for (Usuario usuario : usuarios) {
                bw.writeObject(usuario);
            }
             
             bw.flush();
             
        } catch (Exception e) {
            
        }finally{
            
            try {
                bw.close();
                fr.close();
            } catch (Exception e) {
            }
        }
        
        JOptionPane.showMessageDialog(this, "Usuario Creado");
        
        
        if(artistaCheck.isSelected()==false){
            this.setVisible(false);
        
        tp_cliente.pack();    
        tp_cliente.setModal(true);
        tp_cliente.setLocationRelativeTo(this);
        tp_cliente.setVisible(true);
        }else{
            this.setVisible(false);
        
        tp_artista.pack();    
        tp_artista.setModal(true);
        tp_artista.setLocationRelativeTo(this);
        tp_artista.setVisible(true);
        }
        
        
        
        
        
        
    }//GEN-LAST:event_btn_crearUsuarioMouseClicked

    private void cb_usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_usersMouseClicked
        
    }//GEN-LAST:event_cb_usersMouseClicked

    private void txt_contraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contraActionPerformed

    private void btn_iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_iniciarMouseClicked
       
        int usuario = cb_users.getSelectedIndex();
        
        
        for (int i = 0; i < usuarios.size(); i++) {
            if(usuarios.get(i)==usuarios.get(usuario)){
           
                if(usuarios.get(usuario) instanceof Artistas){
                   if(txt_contra.getText() == null ? usuarios.get(usuario).getContraseña() == null : txt_contra.getText().equals(usuarios.get(usuario).getContraseña())){
                    JOptionPane.showMessageDialog(this, "contra god");
                       this.setVisible(false);
        
                        tp_artista.pack();    
                        tp_artista.setModal(true);
                        tp_artista.setLocationRelativeTo(this);
                        tp_artista.setVisible(true);
                    
                }else{
                    JOptionPane.showMessageDialog(this, "contra erronea");
                } 
                }
                
                if(usuarios.get(usuario) instanceof Cliente){
                   if(txt_contra.getText() == null ? usuarios.get(usuario).getContraseña() == null : txt_contra.getText().equals(usuarios.get(usuario).getContraseña())){
                    JOptionPane.showMessageDialog(this, "contra god");
                     this.setVisible(false);
        
                    tp_cliente.pack();    
                    tp_cliente.setModal(true);
                    tp_cliente.setLocationRelativeTo(this);
                    tp_cliente.setVisible(true);

                }else{
                    JOptionPane.showMessageDialog(this, "contra erronea");
                } 
                }
                
           
             }
        }
        
    }//GEN-LAST:event_btn_iniciarMouseClicked

    private void txt_titActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_titActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_titActionPerformed

    private void btn_lanzamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lanzamientoMouseClicked
       
        
         String titulo = txt_tit.getText();
        String fecha = txt_fechaCrear.getText();
     //   String tituloCancion = txt_titulo.getText();
    //    double segundos = Double.parseDouble(txt_tiempo.getText());
        
        lanza = new Lanzamiento(titulo, fecha, 0);
        
        
        
        
        lanzas.add(lanza);
        
         DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_lanza.getModel();
        
        for (int i = 0; i < lanzas.size(); i++) {
            Object ob = lanzas.get(i);
            modelo.addElement(ob);
        }
        
        cb_lanza.setModel(modelo);
    }//GEN-LAST:event_btn_lanzamientoMouseClicked

    private void btn_cancionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancionMouseClicked
        
       
         String titulo = txt_tit.getText();
        String fecha = txt_fechaCrear.getText();
        String tituloCancion = txt_titulo.getText();
        double segundos = Double.parseDouble(txt_tiempo.getText());
        
        
        for (int i = 0; i < lanzas.size(); i++) {
            if(lanzas.get(i) instanceof Album){
                
            }
        }
        cancion = new Cancion(fecha, segundos, lanza);
        cancioness.add(cancion); 
        
    
        
        
       
        
        
        
    }//GEN-LAST:event_btn_cancionMouseClicked

    private void cb_elegirItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_elegirItemStateChanged
                
        int num = cb_elegir.getSelectedIndex();
        
        if (num == 0) {
            
        }
       
        
    }//GEN-LAST:event_cb_elegirItemStateChanged

    private void cb_lanzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_lanzaMouseClicked
       
    }//GEN-LAST:event_cb_lanzaMouseClicked

    private void btn_arbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_arbolMouseClicked
        DefaultTreeModel modelo = (DefaultTreeModel) arbol.getModel();
        
        for (Lanzamiento Lanzamiento1 : lanzas) {
            DefaultMutableTreeNode referencia = ((DefaultMutableTreeNode) ((DefaultMutableTreeNode) modelo.getRoot()).getChildAt(0));
            DefaultMutableTreeNode nodo = new DefaultMutableTreeNode(Lanzamiento1);
            for (Cancion cancion : cancioness) {
                nodo.add(new DefaultMutableTreeNode(cancion));
            }
            referencia.add(nodo);
        }
    }//GEN-LAST:event_btn_arbolMouseClicked

    public void fillCB(){
        File Archivo;
        FileInputStream fr ;
        ObjectInputStream bw;
        
        
        try {
            Archivo  = new File ("./Usuarios.JD");
            fr = new FileInputStream(Archivo);
            bw = new ObjectInputStream(fr);
            
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_users.getModel();
            
            modelo.removeAllElements();
            
            Object x;
            Usuario a;
            
            while((a=(Usuario)bw.readObject()) != null){
                
                
                
                modelo.addElement(a.getUsername());
                usuarios.add(a);
            }
            
            
            
            
            bw.close();
            fr.close();
            
            cb_users.setModel(modelo);
            
        } catch (Exception e) {
    
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbol;
    private javax.swing.JCheckBox artistaCheck;
    private javax.swing.JButton btn_arbol;
    private javax.swing.JButton btn_cancion;
    private javax.swing.JButton btn_crearUsuario;
    private javax.swing.JButton btn_finalizar;
    private javax.swing.JButton btn_iniciar;
    private javax.swing.JButton btn_lanzamiento;
    private javax.swing.JDialog canciones;
    private javax.swing.JComboBox<String> cb_elegir;
    private javax.swing.JComboBox<String> cb_lanza;
    private javax.swing.JComboBox<String> cb_users;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JDialog tp_artista;
    private javax.swing.JDialog tp_cliente;
    private javax.swing.JTextField txt_contra;
    private javax.swing.JTextField txt_contraseña;
    private javax.swing.JSpinner txt_edad;
    private javax.swing.JTextField txt_fechaCrear;
    private javax.swing.JTextField txt_nombreArtistico;
    private javax.swing.JTextField txt_tiempo;
    private javax.swing.JTextField txt_tit;
    private javax.swing.JTextField txt_titulo;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
